"""
================================================================================
AI-PerfBench  —  Visual Web Dashboard
================================================================================
Standalone Flask app that reads the JSON report produced by perf_bench.py and
renders a full dark-mode, neon-accented benchmark dashboard.

Usage:
    pip install flask
    python app.py                          # looks for results.json by default
    python app.py --report my_bench.json   # custom path
    python app.py --report results.json --port 8080

Then open:  http://localhost:5000
================================================================================
"""

import argparse
import json
import os
import sys
from pathlib import Path
from flask import Flask, render_template_string, jsonify, abort

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="AI-PerfBench Web Dashboard")
parser.add_argument(
    "--report",
    default="results.json",
    metavar="PATH",
    help="Path to the JSON report generated by perf_bench.py (default: results.json)",
)
parser.add_argument(
    "--port",
    type=int,
    default=5000,
    metavar="PORT",
    help="Port to serve the dashboard on (default: 5000)",
)
parser.add_argument(
    "--host",
    default="127.0.0.1",
    metavar="HOST",
    help="Host to bind to (default: 127.0.0.1)",
)
args, _ = parser.parse_known_args()

REPORT_PATH = Path(args.report)

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Data loader
# ---------------------------------------------------------------------------

def load_report() -> dict:
    if not REPORT_PATH.exists():
        abort(404, description=f"Report file not found: {REPORT_PATH.resolve()}")
    with open(REPORT_PATH, "r") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Dashboard HTML template
# ---------------------------------------------------------------------------

DASHBOARD_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>AI-PerfBench — Performance Dashboard</title>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Syne:wght@400;600;700;800&display=swap" rel="stylesheet"/>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
:root {
  --bg:        #090c0f;
  --bg2:       #0e1318;
  --bg3:       #141b22;
  --border:    rgba(0,255,170,0.12);
  --border2:   rgba(0,255,170,0.25);
  --neon:      #00ffaa;
  --neon2:     #00d4ff;
  --neon3:     #ff4d6d;
  --text:      #c8d8e8;
  --text2:     #7a90a4;
  --text3:     #3e5060;
  --mono:      'Share Tech Mono', monospace;
  --sans:      'Syne', sans-serif;
  --glow:      0 0 18px rgba(0,255,170,0.35);
  --glow2:     0 0 18px rgba(0,212,255,0.3);
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html { scroll-behavior: smooth; }

body {
  background: var(--bg);
  color: var(--text);
  font-family: var(--sans);
  min-height: 100vh;
  overflow-x: hidden;
}

/* Scanline overlay */
body::before {
  content:'';
  position:fixed; inset:0;
  background: repeating-linear-gradient(
    0deg,
    transparent,
    transparent 2px,
    rgba(0,0,0,0.07) 2px,
    rgba(0,0,0,0.07) 4px
  );
  pointer-events:none;
  z-index:9999;
}

/* Grid background */
body::after {
  content:'';
  position:fixed; inset:0;
  background-image:
    linear-gradient(rgba(0,255,170,0.025) 1px, transparent 1px),
    linear-gradient(90deg, rgba(0,255,170,0.025) 1px, transparent 1px);
  background-size: 40px 40px;
  pointer-events:none;
  z-index:0;
}

/* ── Layout ─────────────────────────────────────────── */

.shell {
  position:relative; z-index:1;
  max-width: 1320px;
  margin: 0 auto;
  padding: 0 28px 60px;
}

/* ── Header ─────────────────────────────────────────── */

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 28px 0 32px;
  border-bottom: 1px solid var(--border);
  flex-wrap: wrap;
  gap: 16px;
}

.header-left { display:flex; align-items:center; gap:18px; }

.logo-mark {
  width: 44px; height: 44px;
  border: 1.5px solid var(--neon);
  border-radius: 8px;
  display:grid; place-items:center;
  box-shadow: var(--glow);
  flex-shrink:0;
}

.logo-mark svg { width:22px; height:22px; }

.brand-title {
  font-size: 1.1rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--neon);
  text-shadow: var(--glow);
}

.brand-sub {
  font-family: var(--mono);
  font-size: 0.7rem;
  color: var(--text2);
  margin-top: 2px;
  letter-spacing: 0.05em;
}

.header-right {
  font-family: var(--mono);
  font-size: 0.72rem;
  color: var(--text2);
  text-align: right;
  line-height: 1.8;
}

.tag {
  display:inline-block;
  background: rgba(0,255,170,0.08);
  border: 1px solid var(--border2);
  color: var(--neon);
  font-family: var(--mono);
  font-size: 0.65rem;
  padding: 2px 8px;
  border-radius: 4px;
  letter-spacing: 0.08em;
}

/* ── Section title ───────────────────────────────────── */

.section-label {
  font-family: var(--mono);
  font-size: 0.65rem;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--text3);
  margin: 40px 0 16px;
}

.section-label span {
  color: var(--neon);
  margin-right: 8px;
}

/* ── KPI Cards ───────────────────────────────────────── */

.kpi-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 16px;
}

.kpi-card {
  background: var(--bg2);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 26px 28px 22px;
  position:relative;
  overflow:hidden;
  transition: border-color 0.25s, transform 0.2s;
  animation: fadeUp 0.5s ease both;
}

.kpi-card:hover {
  border-color: var(--border2);
  transform: translateY(-2px);
}

.kpi-card::before {
  content:'';
  position:absolute;
  top:0; left:0; right:0;
  height: 2px;
  background: linear-gradient(90deg, var(--neon), transparent);
  opacity: 0.7;
}

.kpi-card.cyan::before  { background: linear-gradient(90deg, var(--neon2), transparent); }
.kpi-card.red::before   { background: linear-gradient(90deg, var(--neon3), transparent); }

.kpi-label {
  font-family: var(--mono);
  font-size: 0.65rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--text2);
  margin-bottom: 14px;
}

.kpi-value {
  font-size: 2.8rem;
  font-weight: 800;
  line-height: 1;
  color: var(--neon);
  text-shadow: var(--glow);
  letter-spacing: -0.01em;
}

.kpi-card.cyan .kpi-value { color: var(--neon2); text-shadow: var(--glow2); }

.kpi-unit {
  font-family: var(--mono);
  font-size: 0.8rem;
  color: var(--text2);
  margin-left: 4px;
  font-weight: 400;
}

.kpi-sub {
  font-family: var(--mono);
  font-size: 0.68rem;
  color: var(--text3);
  margin-top: 10px;
}

.kpi-sub b { color: var(--text2); font-weight: 400; }

/* Calibration pill */
.cal-pill {
  display:inline-flex;
  align-items:center;
  gap:6px;
  font-family: var(--mono);
  font-size: 1rem;
  font-weight: 600;
  letter-spacing: 0.06em;
  padding: 6px 14px;
  border-radius: 6px;
  margin-top: 4px;
}

.cal-pill.stable   { color: var(--neon);  background: rgba(0,255,170,0.08); border: 1px solid rgba(0,255,170,0.3); }
.cal-pill.accept   { color: #f0c040;      background: rgba(240,192,64,0.08); border: 1px solid rgba(240,192,64,0.3); }
.cal-pill.highvar  { color: var(--neon3); background: rgba(255,77,109,0.08); border: 1px solid rgba(255,77,109,0.3); }

.cal-dot {
  width:8px; height:8px; border-radius:50%;
  animation: pulse 2s ease-in-out infinite;
}

.stable .cal-dot   { background: var(--neon); }
.accept .cal-dot   { background: #f0c040; }
.highvar .cal-dot  { background: var(--neon3); }

.cal-note {
  font-family: var(--mono);
  font-size: 0.65rem;
  color: var(--text2);
  margin-top: 12px;
  line-height: 1.7;
}

/* ── Chart panel ─────────────────────────────────────── */

.chart-panel {
  background: var(--bg2);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 28px 28px 22px;
  position:relative;
  overflow:hidden;
  animation: fadeUp 0.6s ease both 0.1s;
}

.chart-panel::before {
  content:'';
  position:absolute;
  top:0; left:0; right:0;
  height: 2px;
  background: linear-gradient(90deg, var(--neon2), var(--neon), transparent);
  opacity: 0.6;
}

.chart-header {
  display:flex;
  align-items:center;
  justify-content:space-between;
  margin-bottom: 22px;
  flex-wrap:wrap;
  gap:10px;
}

.chart-title {
  font-size: 0.85rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--text);
}

.legend-row {
  display:flex;
  gap:18px;
  flex-wrap:wrap;
}

.legend-item {
  display:flex;
  align-items:center;
  gap:6px;
  font-family: var(--mono);
  font-size: 0.65rem;
  color: var(--text2);
  letter-spacing:0.05em;
}

.legend-dot {
  width:8px; height:8px; border-radius:50%;
}

.chart-wrap {
  position:relative;
  height: 320px;
}

/* ── Bottom grid: trial table + system specs ─────────── */

.bottom-grid {
  display: grid;
  grid-template-columns: 1fr 360px;
  gap: 16px;
  align-items: start;
}

@media (max-width: 860px) {
  .bottom-grid { grid-template-columns: 1fr; }
}

/* ── Trial table ─────────────────────────────────────── */

.table-panel {
  background: var(--bg2);
  border: 1px solid var(--border);
  border-radius: 12px;
  overflow:hidden;
  animation: fadeUp 0.6s ease both 0.2s;
}

.table-header-row {
  padding: 18px 24px 12px;
  border-bottom: 1px solid var(--border);
}

.table-title {
  font-size: 0.8rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--text);
}

table {
  width:100%;
  border-collapse: collapse;
}

thead th {
  font-family: var(--mono);
  font-size: 0.6rem;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--text3);
  padding: 10px 20px;
  text-align: right;
  border-bottom: 1px solid var(--border);
  font-weight: 400;
}

thead th:first-child { text-align:left; }

tbody tr {
  border-bottom: 1px solid rgba(0,255,170,0.04);
  transition: background 0.15s;
}

tbody tr:last-child { border-bottom:none; }
tbody tr:hover { background: rgba(0,255,170,0.03); }

tbody td {
  font-family: var(--mono);
  font-size: 0.72rem;
  color: var(--text2);
  padding: 11px 20px;
  text-align: right;
}

tbody td:first-child { text-align:left; color: var(--text); }

.cold-row td { color: rgba(255,77,109,0.8); }
.cold-row td:first-child { color: var(--neon3); }
.cold-badge {
  display:inline-block;
  background: rgba(255,77,109,0.1);
  border: 1px solid rgba(255,77,109,0.3);
  color: var(--neon3);
  font-family: var(--mono);
  font-size: 0.55rem;
  padding: 1px 5px;
  border-radius:3px;
  margin-left: 6px;
  letter-spacing:0.08em;
  vertical-align: middle;
}

.ss-badge {
  display:inline-block;
  background: rgba(0,255,170,0.08);
  border: 1px solid rgba(0,255,170,0.2);
  color: var(--neon);
  font-family: var(--mono);
  font-size: 0.55rem;
  padding: 1px 5px;
  border-radius:3px;
  margin-left: 6px;
  letter-spacing:0.08em;
  vertical-align: middle;
}

.val-good { color: var(--neon); }
.val-warn { color: #f0c040; }

/* ── System specs ────────────────────────────────────── */

.specs-panel {
  background: var(--bg2);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 22px 24px 18px;
  animation: fadeUp 0.6s ease both 0.25s;
}

.specs-title {
  font-size: 0.8rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--text);
  margin-bottom: 18px;
  padding-bottom: 12px;
  border-bottom: 1px solid var(--border);
}

.spec-row {
  display:flex;
  justify-content:space-between;
  align-items:baseline;
  padding: 9px 0;
  border-bottom: 1px solid rgba(0,255,170,0.04);
  gap:12px;
}

.spec-row:last-child { border-bottom:none; }

.spec-key {
  font-family: var(--mono);
  font-size: 0.65rem;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--text3);
  flex-shrink:0;
}

.spec-val {
  font-family: var(--mono);
  font-size: 0.7rem;
  color: var(--neon2);
  text-align:right;
  word-break:break-all;
}

/* ── CI bar ──────────────────────────────────────────── */

.ci-section {
  background: var(--bg3);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 22px 28px;
  animation: fadeUp 0.6s ease both 0.15s;
}

.ci-title {
  font-family: var(--mono);
  font-size: 0.65rem;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: var(--text3);
  margin-bottom: 16px;
}

.ci-grid {
  display:grid;
  grid-template-columns: 1fr 1fr;
  gap: 18px;
}

@media (max-width:600px) { .ci-grid { grid-template-columns:1fr; } }

.ci-metric-label {
  font-family: var(--mono);
  font-size: 0.65rem;
  color: var(--text2);
  margin-bottom:6px;
  letter-spacing:0.06em;
}

.ci-bar-track {
  height:6px;
  background: var(--bg2);
  border-radius:3px;
  position:relative;
  overflow:visible;
  margin-bottom:8px;
  border: 1px solid var(--border);
}

.ci-bar-fill {
  position:absolute;
  height:100%;
  border-radius:3px;
  background: linear-gradient(90deg, var(--neon2), var(--neon));
  box-shadow: 0 0 8px rgba(0,255,170,0.4);
  transition: width 1s cubic-bezier(0.4,0,0.2,1);
}

.ci-values {
  display:flex;
  justify-content:space-between;
  font-family: var(--mono);
  font-size: 0.62rem;
  color: var(--text3);
}

/* ── Footer ──────────────────────────────────────────── */

.footer {
  border-top: 1px solid var(--border);
  padding: 20px 0 0;
  margin-top: 52px;
  display:flex;
  justify-content:space-between;
  align-items:center;
  flex-wrap:wrap;
  gap:10px;
}

.footer-left {
  font-family: var(--mono);
  font-size: 0.62rem;
  color: var(--text3);
}

.footer-right {
  font-family: var(--mono);
  font-size: 0.62rem;
  color: var(--text3);
}

/* ── Animations ─────────────────────────────────────── */

@keyframes fadeUp {
  from { opacity:0; transform:translateY(14px); }
  to   { opacity:1; transform:translateY(0); }
}

@keyframes pulse {
  0%,100% { opacity:1; transform:scale(1); }
  50%      { opacity:0.5; transform:scale(0.85); }
}

</style>
</head>
<body>
<div class="shell">

  <!-- ── Header ── -->
  <header class="header">
    <div class="header-left">
      <div class="logo-mark">
        <svg viewBox="0 0 24 24" fill="none" stroke="#00ffaa" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
          <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
        </svg>
      </div>
      <div>
        <div class="brand-title">AI-PerfBench</div>
        <div class="brand-sub">Automated Performance Profiler · Sustainable Resource Management</div>
      </div>
    </div>
    <div class="header-right">
      <span class="tag" id="cmd-tag">loading…</span><br/>
      <span id="gen-at" style="margin-top:4px; display:inline-block;"></span>
    </div>
  </header>

  <!-- ── KPI Cards ── -->
  <div class="section-label"><span>//</span> Executive Summary</div>
  <div class="kpi-grid" id="kpi-grid">
    <!-- injected by JS -->
  </div>

  <!-- ── Dual-axis chart ── -->
  <div class="section-label"><span>//</span> Trial Performance Profile — Cold Start vs. Steady State</div>
  <div class="chart-panel">
    <div class="chart-header">
      <div class="chart-title">Latency &amp; Peak RAM per Trial</div>
      <div class="legend-row">
        <div class="legend-item"><div class="legend-dot" style="background:#00ffaa;box-shadow:0 0 6px #00ffaa88;"></div>Wall latency (ms)</div>
        <div class="legend-item"><div class="legend-dot" style="background:#00d4ff;box-shadow:0 0 6px #00d4ff88;"></div>Peak RAM (MB)</div>
        <div class="legend-item"><div class="legend-dot" style="background:#ff4d6d;box-shadow:0 0 6px #ff4d6d88;"></div>Cold start</div>
      </div>
    </div>
    <div class="chart-wrap">
      <canvas id="mainChart"></canvas>
    </div>
  </div>

  <!-- ── Confidence Interval bars ── -->
  <div class="section-label"><span>//</span> Statistical Calibration — 95% Confidence Intervals</div>
  <div class="ci-section">
    <div class="ci-title">Steady-State measurements · 95% CI · t-distribution</div>
    <div class="ci-grid" id="ci-grid">
      <!-- injected by JS -->
    </div>
  </div>

  <!-- ── Bottom: trial table + system specs ── -->
  <div class="section-label"><span>//</span> Trial Breakdown &amp; Environment</div>
  <div class="bottom-grid">

    <!-- Trial table -->
    <div class="table-panel">
      <div class="table-header-row">
        <div class="table-title">Per-Trial Raw Results</div>
      </div>
      <table>
        <thead>
          <tr>
            <th>Trial</th>
            <th>Wall time (ms)</th>
            <th>Peak RSS (MB)</th>
            <th>Mean RSS (MB)</th>
            <th>CPU mean %</th>
            <th>Samples</th>
            <th>Exit</th>
          </tr>
        </thead>
        <tbody id="trial-tbody"></tbody>
      </table>
    </div>

    <!-- System specs -->
    <div class="specs-panel">
      <div class="specs-title">Environment &amp; System Context</div>
      <div id="specs-rows"></div>
    </div>

  </div>

  <!-- Footer -->
  <footer class="footer">
    <div class="footer-left">AI-PerfBench Dashboard · Isolated Process Monitoring Architecture</div>
    <div class="footer-right" id="footer-ts"></div>
  </footer>

</div>

<script>
// ── Fetch data from Flask API ──────────────────────────────────────────────

async function init() {
  let data;
  try {
    const res = await fetch('/api/report');
    if (!res.ok) throw new Error(await res.text());
    data = await res.json();
  } catch(e) {
    document.body.innerHTML = `<div style="font-family:monospace;color:#ff4d6d;padding:60px;font-size:1rem;">
      <b>Error loading report:</b><br/>${e.message}<br/><br/>
      Make sure perf_bench.py has run and produced the report file.</div>`;
    return;
  }

  const agg = data.aggregate || {};
  const sysinfo = data.system_info || {};
  const cold = data.cold_start_trial;
  const ss = data.steady_state_trials || [];
  const allTrials = cold ? [cold, ...ss] : ss;
  const cfg = data.config || {};

  // ── Header ──
  document.getElementById('cmd-tag').textContent = cfg.cmd || '—';
  const genAt = data.generated_at
    ? new Date(data.generated_at).toLocaleString()
    : '—';
  document.getElementById('gen-at').textContent = `Generated: ${genAt}`;
  document.getElementById('footer-ts').textContent = `Report: ${data.title || 'AI-PerfBench'}`;

  // ── KPI Cards ──
  const meanLatMs  = ((agg.ss_wall_time_mean_s || 0) * 1000).toFixed(1);
  const stdLatMs   = ((agg.ss_wall_time_std_s  || 0) * 1000).toFixed(1);
  const meanRamMB  = ((agg.ss_rss_peak_mean_bytes || 0) / 1048576).toFixed(1);
  const stdRamMB   = ((agg.ss_rss_peak_std_bytes  || 0) / 1048576).toFixed(2);
  const cvPct      = ((agg.ss_wall_time_cv || 0) * 100).toFixed(2);
  const trialCount = ss.length;
  const note       = agg.calibration_note || '';

  let calClass = 'stable', calText = 'STABLE';
  if (note.startsWith('ACCEPT'))      { calClass='accept';  calText='ACCEPTABLE'; }
  else if (note.startsWith('HIGH'))   { calClass='highvar'; calText='HIGH VARIANCE'; }

  document.getElementById('kpi-grid').innerHTML = `
    <div class="kpi-card" style="animation-delay:0s">
      <div class="kpi-label">Avg. Steady-State Latency</div>
      <div class="kpi-value">${meanLatMs}<span class="kpi-unit">ms</span></div>
      <div class="kpi-sub">± ${stdLatMs} ms std &nbsp;·&nbsp; <b>N=${trialCount} SS trials</b></div>
    </div>
    <div class="kpi-card cyan" style="animation-delay:0.07s">
      <div class="kpi-label">Avg. Steady-State Peak RAM</div>
      <div class="kpi-value">${meanRamMB}<span class="kpi-unit">MB</span></div>
      <div class="kpi-sub">± ${stdRamMB} MB std &nbsp;·&nbsp; <b>net workload footprint</b></div>
    </div>
    <div class="kpi-card" style="animation-delay:0.14s">
      <div class="kpi-label">System Calibration Status</div>
      <div><div class="cal-pill ${calClass}"><span class="cal-dot"></span>${calText}</div></div>
      <div class="cal-note">CV = ${cvPct}%<br/>${note}</div>
    </div>
    <div class="kpi-card" style="animation-delay:0.21s">
      <div class="kpi-label">Cold-Start Overhead</div>
      ${cold ? `
        <div class="kpi-value" style="color:var(--neon3);text-shadow:0 0 18px rgba(255,77,109,.4);">
          ${(cold.wall_time_s*1000).toFixed(1)}<span class="kpi-unit">ms</span></div>
        <div class="kpi-sub">vs. ${meanLatMs} ms steady &nbsp;·&nbsp;
          <b>×${agg.ss_wall_time_mean_s > 0 ? (cold.wall_time_s/(agg.ss_wall_time_mean_s)).toFixed(2) : '—'} slower</b>
        </div>
      ` : `<div class="kpi-value" style="color:var(--text3);">—</div>`}
    </div>
  `;

  // ── Chart ──
  const labels  = allTrials.map(t => `Trial ${t.trial_index + 1}`);
  const latData = allTrials.map(t => +(t.wall_time_s * 1000).toFixed(2));
  const ramData = allTrials.map(t => +(t.rss_peak_net_bytes / 1048576).toFixed(2));
  const coldIdx = cold ? cold.trial_index : -1;

  const pointBgLat = allTrials.map(t =>
    t.trial_index === coldIdx ? '#ff4d6d' : '#00ffaa');
  const pointBgRam = allTrials.map(t =>
    t.trial_index === coldIdx ? '#ff4d6d' : '#00d4ff');
  const pointRadius = allTrials.map(t =>
    t.trial_index === coldIdx ? 7 : 4);

  const ctx = document.getElementById('mainChart').getContext('2d');

  // Cold-start annotation plugin (inline)
  const coldAnnotation = {
    id: 'coldBand',
    beforeDraw(chart) {
      if (coldIdx < 0) return;
      const { ctx: c, chartArea: { top, bottom }, scales } = chart;
      const x = scales.x.getPixelForValue(coldIdx);
      c.save();
      c.fillStyle = 'rgba(255,77,109,0.06)';
      c.fillRect(x - 28, top, 56, bottom - top);
      c.strokeStyle = 'rgba(255,77,109,0.25)';
      c.setLineDash([4, 3]);
      c.lineWidth = 1;
      c.beginPath(); c.moveTo(x, top); c.lineTo(x, bottom); c.stroke();
      c.setLineDash([]);
      c.restore();
    }
  };

  new Chart(ctx, {
    type: 'line',
    plugins: [coldAnnotation],
    data: {
      labels,
      datasets: [
        {
          label: 'Wall latency (ms)',
          data: latData,
          yAxisID: 'yLat',
          borderColor: '#00ffaa',
          backgroundColor: 'rgba(0,255,170,0.08)',
          borderWidth: 2,
          pointBackgroundColor: pointBgLat,
          pointBorderColor: pointBgLat,
          pointRadius,
          pointHoverRadius: 7,
          fill: true,
          tension: 0.35,
        },
        {
          label: 'Peak RAM (MB)',
          data: ramData,
          yAxisID: 'yRam',
          borderColor: '#00d4ff',
          backgroundColor: 'rgba(0,212,255,0.05)',
          borderWidth: 2,
          pointBackgroundColor: pointBgRam,
          pointBorderColor: pointBgRam,
          pointRadius,
          pointHoverRadius: 7,
          fill: true,
          tension: 0.35,
          borderDash: [5, 3],
        }
      ]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      interaction: { mode: 'index', intersect: false },
      plugins: {
        legend: { display: false },
        tooltip: {
          backgroundColor: '#0e1318',
          borderColor: 'rgba(0,255,170,0.25)',
          borderWidth: 1,
          titleColor: '#c8d8e8',
          titleFont: { family: "'Share Tech Mono',monospace", size: 12 },
          bodyColor: '#7a90a4',
          bodyFont: { family: "'Share Tech Mono',monospace", size: 11 },
          padding: 12,
          callbacks: {
            label: ctx => {
              const suffix = ctx.datasetIndex === 0 ? ' ms' : ' MB';
              return `  ${ctx.dataset.label}: ${ctx.parsed.y}${suffix}`;
            }
          }
        }
      },
      scales: {
        x: {
          ticks: {
            color: '#3e5060',
            font: { family: "'Share Tech Mono',monospace", size: 11 },
          },
          grid: { color: 'rgba(0,255,170,0.04)' },
          border: { color: 'rgba(0,255,170,0.1)' },
        },
        yLat: {
          position: 'left',
          title: {
            display: true,
            text: 'Wall time (ms)',
            color: '#00ffaa',
            font: { family: "'Share Tech Mono',monospace", size: 10 },
          },
          ticks: {
            color: '#00ffaa',
            font: { family: "'Share Tech Mono',monospace", size: 10 },
          },
          grid: { color: 'rgba(0,255,170,0.04)' },
          border: { color: 'rgba(0,255,170,0.1)' },
        },
        yRam: {
          position: 'right',
          title: {
            display: true,
            text: 'Peak RAM (MB)',
            color: '#00d4ff',
            font: { family: "'Share Tech Mono',monospace", size: 10 },
          },
          ticks: {
            color: '#00d4ff',
            font: { family: "'Share Tech Mono',monospace", size: 10 },
          },
          grid: { drawOnChartArea: false },
          border: { color: 'rgba(0,212,255,0.15)' },
        }
      }
    }
  });

  // ── CI bars ──
  const ciLatLo  = (agg.ss_wall_time_ci95_low  || 0) * 1000;
  const ciLatHi  = (agg.ss_wall_time_ci95_high || 0) * 1000;
  const ciRamLo  = (agg.ss_rss_ci95_low  || 0) / 1048576;
  const ciRamHi  = (agg.ss_rss_ci95_high || 0) / 1048576;
  const latRange = Math.max(ciLatHi * 1.2, 0.001);
  const ramRange = Math.max(ciRamHi * 1.2, 0.001);
  const latLoP   = Math.max(0, Math.min(100, (ciLatLo / latRange) * 100)).toFixed(1);
  const latHiP   = Math.max(0, Math.min(100, (ciLatHi / latRange) * 100)).toFixed(1);
  const ramLoP   = Math.max(0, Math.min(100, (ciRamLo / ramRange) * 100)).toFixed(1);
  const ramHiP   = Math.max(0, Math.min(100, (ciRamHi / ramRange) * 100)).toFixed(1);

  document.getElementById('ci-grid').innerHTML = `
    <div>
      <div class="ci-metric-label">Wall-time latency — 95% CI</div>
      <div class="ci-bar-track">
        <div class="ci-bar-fill" style="left:${latLoP}%; width:${latHiP - latLoP}%;"></div>
      </div>
      <div class="ci-values"><span>${ciLatLo.toFixed(2)} ms</span><span>${ciLatHi.toFixed(2)} ms</span></div>
    </div>
    <div>
      <div class="ci-metric-label">Peak RAM — 95% CI</div>
      <div class="ci-bar-track">
        <div class="ci-bar-fill" style="left:${ramLoP}%; width:${ramHiP - ramLoP}%;"></div>
      </div>
      <div class="ci-values"><span>${ciRamLo.toFixed(2)} MB</span><span>${ciRamHi.toFixed(2)} MB</span></div>
    </div>
  `;

  // ── Trial table ──
  let tbody = '';
  for (const t of allTrials) {
    const isCold = t.trial_index === coldIdx;
    const cls    = isCold ? 'cold-row' : '';
    const badge  = isCold
      ? '<span class="cold-badge">COLD</span>'
      : '<span class="ss-badge">SS</span>';
    const latMs  = (t.wall_time_s * 1000).toFixed(2);
    const pkMB   = (t.rss_peak_net_bytes  / 1048576).toFixed(2);
    const mnMB   = (t.rss_mean_net_bytes  / 1048576).toFixed(2);
    const cpu    = t.cpu_mean_percent.toFixed(1);
    const samples= t.sample_count || (t.samples_summary && t.samples_summary.count) || '—';
    const exit   = t.exit_code === 0
      ? '<span class="val-good">0</span>'
      : `<span class="val-warn">${t.exit_code}</span>`;
    tbody += `
      <tr class="${cls}">
        <td>Trial ${t.trial_index+1}${badge}</td>
        <td>${latMs}</td>
        <td>${pkMB}</td>
        <td>${mnMB}</td>
        <td>${cpu}</td>
        <td>${samples}</td>
        <td>${exit}</td>
      </tr>`;
  }
  document.getElementById('trial-tbody').innerHTML = tbody;

  // ── System specs ──
  const specMap = [
    ['Platform',       sysinfo.platform      || '—'],
    ['Python',         sysinfo.python_version || '—'],
    ['CPU cores',      `${sysinfo.cpu_logical_cores || '—'} logical / ${sysinfo.cpu_physical_cores || '—'} physical`],
    ['CPU freq',       sysinfo.cpu_freq_mhz ? `${sysinfo.cpu_freq_mhz} MHz` : '—'],
    ['Total RAM',      sysinfo.total_ram_gb  ? `${sysinfo.total_ram_gb} GB` : '—'],
    ['Avail. RAM',     sysinfo.available_ram_gb ? `${sysinfo.available_ram_gb} GB` : '—'],
    ['Hostname',       sysinfo.hostname || '—'],
    ['NumPy/SciPy',    sysinfo.numpy_available ? 'Available' : 'Fallback mode'],
    ['Trials (total)', cfg.trials || '—'],
    ['Sample interval',cfg.sample_interval_s ? `${(cfg.sample_interval_s*1000).toFixed(2)} ms` : '—'],
    ['Outlier z-score',cfg.outlier_z_threshold || '—'],
  ];
  document.getElementById('specs-rows').innerHTML = specMap.map(([k,v]) => `
    <div class="spec-row">
      <div class="spec-key">${k}</div>
      <div class="spec-val">${v}</div>
    </div>`).join('');
}

init();
</script>
</body>
</html>
"""

# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def dashboard():
    return render_template_string(DASHBOARD_HTML)


@app.route("/api/report")
def api_report():
    return jsonify(load_report())


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print(f"""
╔══════════════════════════════════════════════════════╗
║         AI-PerfBench  —  Visual Dashboard            ║
╠══════════════════════════════════════════════════════╣
║  Report  : {str(REPORT_PATH.resolve())[:42]:<42} ║
║  Address : http://{args.host}:{args.port:<4}                        ║
╚══════════════════════════════════════════════════════╝
""")

    if not REPORT_PATH.exists():
        print(f"  ⚠  WARNING: report file not found → {REPORT_PATH.resolve()}")
        print("     Run perf_bench.py --output results.json first.\n")

    app.run(host=args.host, port=args.port, debug=False)
